kind: Service
apiVersion: v1
metadata:
  name: ecommerce-api
  namespace: dev 
  labels:
    app: ecommerce-api
spec:
  type: NodePort
  selector:
    app: ecommerce-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31472
